#ifndef _ADCV_EXIT_CODES_
#define _ADCV_EXIT_CODES_

enum ADCV_EXIT_CODES {
    ADCV_EXIT_SUCCESS,
    ADCV_SEMGET_FAIL,
    ADCV_SEMCTL_FAIL,
    ADCV_SEMOP_FAIL,
    TCP_LOOP_NULL_CONNECTION_INSTANCE
};

#endif /* _ADCV_EXIT_CODES_ */
